# -*- coding: utf-8 -*-
"""REVIEW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVXzqhzV71lttmfVpcyYxcwvl5DcYyJN
"""

# Import Libraries
import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load Dataset
data = pd.read_csv('/content/amazon.csv')

# Step 3: Display Dataset Information
print("Dataset Shape:", data.shape)
print(data.head())

# Step 4: Select Features and Target
X = data['Review_text']
y = data['Own_Rating']

# Text Cleaning Function
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    return text

# Step 6: Clean Reviews
X = X.apply(clean_text)

# Step 7: TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english')
X_tfidf = vectorizer.fit_transform(X)

# Step 8: Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.20,
    random_state=42
)

# Step 9: Train Logistic Regression Model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Step 10: Prediction
y_pred = model.predict(X_test)

# Step 11: Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

# Step 12: Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred))

# Step 13: Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

"""**Sentiment Prediction for New Review**"""

new_review = ["This product is amazing and worth buying"]

new_review_tfidf = vectorizer.transform(new_review)

prediction = model.predict(new_review_tfidf)

print("Predicted Sentiment:", prediction[0])

import matplotlib.pyplot as plt

data['Own_Rating'].value_counts().plot(
    kind='bar'
)

plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()